# Generated by Django 4.0.4 on 2022-07-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=30, null=True)),
                ('precision', models.FloatField(null=True)),
                ('auto_chunks', models.BooleanField(default=True)),
                ('packed', models.BooleanField(default=True)),
                ('unique_times', models.BooleanField(default=True)),
                ('remove_existing_folder', models.BooleanField(default=False)),
                ('chunks', models.CharField(max_length=1000, null=True)),
                ('timeout', models.IntegerField(default=600)),
                ('intake_source', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=30, null=True)),
                ('combine', models.BooleanField(default=False)),
                ('timeout', models.IntegerField(default=600)),
                ('intake_source', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonWorkflowJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('exception', models.CharField(max_length=10000, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('json_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.jsonworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('complete_conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.completeconversion')),
                ('intake_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.intakecatalog')),
                ('json_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.jsonworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='CompleteConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('exception', models.CharField(max_length=10000, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('complete_conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.completeconversion')),
            ],
        ),
    ]
