# Generated by Django 4.0.3 on 2022-04-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonWorkflow',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonWorkflowJob',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('json_workflow', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='db.jsonworkflow')),
            ],
        ),
    ]
