# Generated by Django 4.0.4 on 2022-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakecatalog',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
