# Generated by Django 4.0.3 on 2022-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_jsonworkflow_name_jsonworkflowjob_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonworkflowjob',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='input',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='job_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='output',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
