# Generated by Django 4.0.4 on 2022-07-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_intakecatalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakesource',
            name='complete_conversion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.completeconversion'),
        ),
        migrations.AlterField(
            model_name='intakesource',
            name='json_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.jsonworkflow'),
        ),
    ]
