# Generated by Django 4.0.3 on 2022-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_name_jsonworkflowjob_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
