# Generated by Django 4.0.3 on 2022-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_jsonworkflowjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflow',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
