# Generated by Django 4.0.3 on 2022-04-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_jsonworkflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonworkflowjob',
            name='json_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.jsonworkflow'),
        ),
    ]
