# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_jsonworkflowjob_json_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='exception',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
