# Generated by Django 4.0.4 on 2022-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_jsonworkflowjob_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
