# Generated by Django 4.0.4 on 2022-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_jsonworkflowjob_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
