# Generated by Django 4.0.4 on 2022-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_jsonworkflowjob_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflowjob',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
