# Generated by Django 4.0.4 on 2022-05-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_jsonworkflowjob_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('file_name', models.CharField(max_length=200)),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('exception', models.CharField(max_length=10000, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('complete_conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.completeconversion')),
            ],
        ),
    ]
