# Generated by Django 4.0.4 on 2022-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_completeconversion_completeconversionjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonworkflow',
            name='status',
        ),
        migrations.AddField(
            model_name='jsonworkflow',
            name='combine',
            field=models.BooleanField(default=False),
        ),
    ]
