# Generated by Django 4.0.4 on 2022-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_remove_jsonworkflow_status_jsonworkflow_combine'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflow',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
