# Generated by Django 4.0.4 on 2022-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_jsonworkflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeconversion',
            name='auto_chunks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='completeconversion',
            name='chunks',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='completeconversion',
            name='packed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='completeconversion',
            name='precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='completeconversion',
            name='uniqueTimes',
            field=models.BooleanField(default=True),
        ),
    ]
