# Generated by Django 4.0.4 on 2022-05-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_completeconversion_auto_chunks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeconversion',
            old_name='uniqueTimes',
            new_name='unique_times',
        ),
    ]
