# Generated by Django 4.0.4 on 2022-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_completeconversion_remove_existing_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeconversion',
            name='timeout',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='jsonworkflow',
            name='timeout',
            field=models.IntegerField(default=600),
        ),
    ]
