# Generated by Django 4.0.4 on 2022-07-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_completeconversion_timeout_jsonworkflow_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='completeconversion',
            name='intake_source',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jsonworkflow',
            name='intake_source',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='IntakeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('intake_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.intakecatalog')),
            ],
        ),
    ]
