# Generated by Django 4.0.4 on 2022-07-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_intakecatalog_completeconversion_intake_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesource',
            name='complete_conversion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='db.completeconversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakesource',
            name='json_workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.jsonworkflow'),
            preserve_default=False,
        ),
    ]
